### ISSUE TITLE
Unable to delete Accounts

### ISSUE THREAD

**Issue by m3techitopsadmin** [jackjoe/mailgun_logger#18]
> 02:42:14.783 [info] DELETE /accounts/8
> 02:42:14.801 [info] Sent 500 in 18ms
> 02:42:14.802 [error] #PID<0.3618.0> running MailgunLoggerWeb.Endpoint (connection #PID<0.3547.0>, stream id 21) terminated
> Server: <url>:5050 (http)
> Request: POST /accounts/8
> ** (exit) an exception was raised:
>     ** (Ecto.ConstraintError) constraint error when attempting to delete struct:
> 
>     * events_account_id_fkey (foreign_key_constraint)
> 
> If you would like to stop this constraint violation from raising an
> exception and instead add it as an error to your changeset, please
> call `foreign_key_constraint/3` on your changeset with the constraint
> `:name` as an option.

Getting this error when trying to delete accounts

**Comment by jeroenbourgois** [comment]
@m3techitopsadmin thanks. It's because there are still events for that account and the proper cascade is not set. However I cannot reproduce this on my side...

I updated the migration none the less, but it might be better if you set the CASCADE option on your database yourself, so that when you delete an account any referencing events are deleted too.

**Comment by jeroenbourgois** [comment]
You can look here for examples: https://www.mysqltutorial.org/mysql-on-delete-cascade/
